# Generated by Django 6.0.6 on 2026-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmaraprojapp', '0003_paymentotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_img.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
